"""
Train brain state prediction model on HCP resting-state fMRI.

Reads a manifest CSV generated by prepare_dataset.py.
Downloads and preprocesses sessions from S3 on-demand; caches preprocessed npy files.

Usage (single session, already cached):
  python train.py --manifest data/manifest.csv --cache_dir data/ --window 30 --epochs 20 --wandb

Usage (bubble mode):
  python train.py --manifest data/manifest.csv --cache_dir data/ --n_cortical 360 --n_subcortical 19
"""

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path

import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import hcp_utils as hcp
import wandb

from model import TimeSeriesTransformer
from bubble_parc import BubbleParcellation, bubble_regularizers


# ── args ────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--manifest",      required=True, help="Manifest CSV from prepare_dataset.py")
    p.add_argument("--cache_dir",     default="data/",
                   help="Directory for preprocessed npy files (downloaded on demand)")

    # training
    p.add_argument("--window",        type=int,   default=30)
    p.add_argument("--epochs",        type=int,   default=20)
    p.add_argument("--batch_size",    type=int,   default=64)
    p.add_argument("--lr",            type=float, default=1e-4)

    # model
    p.add_argument("--dim_val",       type=int,   default=760)
    p.add_argument("--n_heads",       type=int,   default=8)
    p.add_argument("--n_enc",         type=int,   default=4)
    p.add_argument("--n_dec",         type=int,   default=4)

    # loss / eval
    p.add_argument("--loss",          default="mc_raw", choices=["mmp", "mc_raw"])
    p.add_argument("--mc_samples",    type=int,   default=200)
    p.add_argument("--mc_draws",      type=int,   default=20)
    p.add_argument("--benchmarks",    nargs="+",  default=["mmp", "mc_raw"],
                   choices=["mmp", "mc_raw", "full_raw"])

    # bubble mode
    p.add_argument("--n_cortical",    type=int,   default=None,
                   help="Cortical bubbles — enables bubble mode (default atlas: 360)")
    p.add_argument("--n_subcortical", type=int,   default=None,
                   help="Subcortical bubbles (default atlas: 19)")
    p.add_argument("--lam_coverage",  type=float, default=0.0)
    p.add_argument("--lam_overlap",   type=float, default=0.0)
    p.add_argument("--lam_radius",    type=float, default=0.0)

    # output — run dir is auto-named; override with --run_dir
    p.add_argument("--run_dir",       default=None,
                   help="Output directory for this run (default: data/<auto-named>/)")

    # wandb
    p.add_argument("--wandb",         action="store_true")
    p.add_argument("--wandb_project", default="brain-state-pred")
    p.add_argument("--wandb_name",    default=None)

    p.add_argument("--log_every",     type=int, default=10,
                   help="Print step-level loss every N batches (0 = off)")

    return p.parse_args()


# ── manifest ────────────────────────────────────────────────────────────────────

def load_manifest(manifest_path):
    path = Path(manifest_path)
    rows = []
    with open(path) as f:
        for row in csv.DictReader(f):
            row["tp_start"] = int(row["tp_start"])
            row["tp_end"]   = int(row["tp_end"])
            rows.append(row)

    params_path = path.with_name(path.stem + "_params.json")
    if params_path.exists():
        with open(params_path) as f:
            params = json.load(f)
    else:
        params = {"tr": 0.72, "lowcut": 0.01, "highcut": 0.1, "filter_order": 4}
        print(f"Warning: {params_path} not found — using default preprocessing params")

    return rows, params




# ── dataset ─────────────────────────────────────────────────────────────────────

class MultiSessionDataset(Dataset):
    """
    Flat index over all (session, window_offset) pairs across multiple sessions.
    Uses memory-mapped npy for efficient access without loading everything into RAM.
    """
    def __init__(self, session_entries, window):
        # session_entries: list of (parc_mmap, raw_mmap_or_None, tp_start, tp_end)
        self.window = window
        self.parcs  = []
        self.raws   = []
        self.index  = []

        for i, (parc_mm, raw_mm, tp_start, tp_end) in enumerate(session_entries):
            n_tps = tp_end - tp_start
            self.parcs.append(parc_mm[tp_start:tp_end])
            self.raws.append(raw_mm[tp_start:tp_end] if raw_mm is not None else None)
            for w in range(n_tps - window):
                self.index.append((i, w))

    def __len__(self):
        return len(self.index)

    def __getitem__(self, idx):
        sess_i, w = self.index[idx]
        W  = self.window
        parc = self.parcs[sess_i]
        x_parc = torch.from_numpy(parc[w : w + W].copy())              # (W, 379)
        y_parc = torch.from_numpy(parc[w + W : w + W + 1].copy())      # (1, 379)

        raw = self.raws[sess_i]
        if raw is not None:
            x_raw = torch.from_numpy(raw[w : w + W].copy())            # (W, G)
            y_raw = torch.from_numpy(raw[w + W : w + W + 1].copy())    # (1, G)
        else:
            x_raw = torch.empty(0)
            y_raw = torch.empty(0)

        return x_parc, x_raw, y_parc, y_raw


# ── atlas helpers ────────────────────────────────────────────────────────────────

def build_parcel_to_gray(labels, valid_mask):
    valid_idx  = np.where(valid_mask)[0]
    parcel_idx = labels[valid_idx] - 1
    return valid_idx, parcel_idx


def reparcellate(pred_g, valid_gray_idx, parcel_for_gray, N_parc):
    B, device  = pred_g.shape[0], pred_g.device
    g_idx      = valid_gray_idx
    p_idx      = parcel_for_gray
    out        = torch.zeros(B, 1, N_parc, device=device)
    cnt        = torch.zeros(N_parc, device=device)
    cnt.scatter_add_(0, p_idx, torch.ones(len(p_idx), dtype=torch.float32, device=device))
    out.scatter_add_(2, p_idx.unsqueeze(0).unsqueeze(0).expand(B, 1, -1), pred_g[:, :, g_idx])

    return out / cnt.clamp(min=1)


# ── loss helpers ─────────────────────────────────────────────────────────────────

def mc_raw_loss_fixed(pred, y_raw, valid_gray_idx, parcel_for_gray, k):
    sample      = torch.randint(0, len(valid_gray_idx), (k,), device=pred.device)
    pred_at_g   = pred[:, :, parcel_for_gray[sample]]
    actual_at_g = y_raw[:, :, valid_gray_idx[sample]]
    return nn.functional.mse_loss(pred_at_g, actual_at_g)


def mc_raw_loss_bubble(pred, y_raw, W_c, W_s, N_c, G_c, k):
    G     = G_c + W_s.shape[1]
    idx   = torch.randint(0, G, (k,), device=pred.device)
    c_sel = idx[idx < G_c]
    s_sel = idx[idx >= G_c] - G_c
    parts_pred, parts_actual = [], []
    if c_sel.numel():
        parts_pred.append(pred[:, :, :N_c] @ W_c[:, c_sel])
        parts_actual.append(y_raw[:, :, c_sel])
    if s_sel.numel():
        parts_pred.append(pred[:, :, N_c:] @ W_s[:, s_sel])
        parts_actual.append(y_raw[:, :, G_c + s_sel])
    return nn.functional.mse_loss(torch.cat(parts_pred, -1), torch.cat(parts_actual, -1))


# ── main ─────────────────────────────────────────────────────────────────────────

def main():
    args   = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else
                          "mps"  if torch.backends.mps.is_available() else "cpu")
    print(f"Device: {device}")

    rows, params = load_manifest(args.manifest)
    print(f"Manifest: {len(rows)} rows  |  Params: {params}")

    use_bubbles = (args.n_cortical is not None) or (args.n_subcortical is not None)
    N_c = args.n_cortical    or 360
    N_s = args.n_subcortical or 19
    G_c = 59412
    need_raw = use_bubbles or args.loss == "mc_raw" or \
               "mc_raw" in args.benchmarks or "full_raw" in args.benchmarks

    cache_dir = Path(args.cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)

    # ── atlas ────────────────────────────────────────────────────────────────────
    labels     = hcp.mmp.map_all
    valid_mask = labels > 0
    valid_gray_idx, parcel_for_gray = build_parcel_to_gray(labels, valid_mask)
    valid_gray_idx  = torch.tensor(valid_gray_idx,  dtype=torch.long).to(device)
    parcel_for_gray = torch.tensor(parcel_for_gray, dtype=torch.long).to(device)
    N_parc = int(labels.max())

    # ── verify preprocessed data exists ─────────────────────────────────────────
    session_paths = {}
    for row in rows:
        key = (row["subject_id"], row["session"])
        if key in session_paths:
            continue
        subj, sess = row["subject_id"], row["session"]
        stem      = f"{subj}_{sess}"
        parc_path = cache_dir / f"{stem}_p.npy"
        raw_path  = cache_dir / f"{stem}_raw.npy"
        if not parc_path.exists() or not raw_path.exists():
            raise FileNotFoundError(
                f"Missing preprocessed data for {stem}. "
                f"Run: python prepare_dataset.py ... --download --cache_dir {cache_dir}"
            )
        session_paths[key] = (parc_path, raw_path)

    # ── build datasets ───────────────────────────────────────────────────────────
    def make_entries(split_rows):
        entries = []
        for row in split_rows:
            key = (row["subject_id"], row["session"])
            parc_path, raw_path = session_paths[key]
            parc_mm = np.load(str(parc_path), mmap_mode='r')
            raw_mm  = np.load(str(raw_path),  mmap_mode='r') if need_raw else None
            entries.append((parc_mm, raw_mm, row["tp_start"], row["tp_end"]))
        return entries

    train_rows = [r for r in rows if r["split"] == "train"]
    val_rows   = [r for r in rows if r["split"] == "val"]

    train_ds = MultiSessionDataset(make_entries(train_rows), args.window)
    val_ds   = MultiSessionDataset(make_entries(val_rows),   args.window)
    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,  num_workers=0)
    val_dl   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False, num_workers=0)

    train_tps = sum(r["tp_end"] - r["tp_start"] for r in train_rows)
    val_tps   = sum(r["tp_end"] - r["tp_start"] for r in val_rows)
    print(f"Train: {train_tps} TPs → {len(train_ds)} windows  |  Val: {val_tps} TPs → {len(val_ds)} windows")

    # ── model ────────────────────────────────────────────────────────────────────
    N_model = (N_c + N_s) if use_bubbles else N_parc
    model = TimeSeriesTransformer(
        input_size=N_model, dec_seq_len=1, dim_val=args.dim_val,
        n_heads=args.n_heads, n_encoder_layers=args.n_enc,
        n_decoder_layers=args.n_dec, max_seq_len=args.window,
        out_seq_len=1, num_predicted_features=N_model, batch_first=True,
    ).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model: {n_params/1e6:.2f}M params  ({n_params*4/1e6:.0f} MB fp32)")

    # ── bubble parcellation ───────────────────────────────────────────────────────
    bubble_parc = None
    if use_bubbles:
        coords_c_l, _ = hcp.mesh.sphere_left
        coords_c_r, _ = hcp.mesh.sphere_right
        coords_c = np.vstack([coords_c_l[hcp.vertex_info.grayl],
                               coords_c_r[hcp.vertex_info.grayr]]).astype(np.float32)
        coords_s_path = cache_dir / "subcortical_coords.npy"
        if not coords_s_path.exists():
            raise FileNotFoundError(
                f"{coords_s_path} not found. Run with at least one session so it can be "
                "extracted from the CIFTI before deletion."
            )
        coords_s = np.load(str(coords_s_path))
        bubble_parc = BubbleParcellation(coords_c, coords_s, labels, N_c, N_s).to(device)
        optimizer = torch.optim.Adam(
            list(model.parameters()) + list(bubble_parc.parameters()), lr=args.lr
        )
        mode_str = f"bubble(N_c={N_c}, N_s={N_s})"
    else:
        optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
        mode_str  = args.loss

    mse = nn.MSELoss()
    print(f"Mode: {mode_str}  |  Benchmarks: {args.benchmarks}")

    # ── run directory ─────────────────────────────────────────────────────────────
    if args.run_dir:
        run_dir = Path(args.run_dir)
    else:
        ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
        n_subj   = params.get("n_subjects", len({r["subject_id"] for r in rows}))
        run_name = f"{mode_str.replace('(','').replace(')','').replace(',','').replace(' ','_')}_s{n_subj}_w{args.window}_{ts}"
        run_dir  = Path("data") / run_name
    run_dir.mkdir(parents=True, exist_ok=True)
    print(f"Run dir: {run_dir}")

    # save config snapshot
    run_config = {**vars(args), **{k: v for k, v in params.items()
                                   if k in ("tr","lowcut","highcut","filter_order","val_mode","seed")}}
    with open(run_dir / "config.json", "w") as f:
        json.dump(run_config, f, indent=2)

    if args.wandb:
        wandb.login()
        run_name_wb = args.wandb_name or run_dir.name
        wandb.init(project=args.wandb_project, name=run_name_wb, config=run_config)

    out_path = run_dir / "model.pt"

    # ── training loop ─────────────────────────────────────────────────────────────
    for epoch in range(1, args.epochs + 1):
        model.train()
        if bubble_parc is not None:
            bubble_parc.train()
        train_losses = []

        n_batches = len(train_dl)
        for step, (x_parc, x_raw, y_parc, y_raw) in enumerate(tqdm(train_dl, desc=f"Epoch {epoch}/{args.epochs}", leave=True)):
            x_parc = x_parc.to(device)
            y_parc = y_parc.to(device)
            if need_raw:
                x_raw = x_raw.to(device)
                y_raw = y_raw.to(device)

            if bubble_parc is not None:
                W_c, W_s = bubble_parc.weights()
                x_in     = bubble_parc(x_raw, W_c, W_s)
                dec_in   = x_in[:, -1:, :]
                pred     = model(x_in, dec_in)
                loss     = mc_raw_loss_bubble(pred, y_raw, W_c, W_s, N_c, G_c, args.mc_samples)
                if args.lam_coverage or args.lam_overlap or args.lam_radius:
                    R_cov, R_ov, R_rad = bubble_regularizers(W_c, W_s,
                                                              bubble_parc.log_r_c, bubble_parc.log_r_s)
                    loss = loss + args.lam_coverage*R_cov + args.lam_overlap*R_ov + args.lam_radius*R_rad
            else:
                x_in   = x_parc
                dec_in = x_in[:, -1:, :]
                pred   = model(x_in, dec_in)
                if args.loss == "mmp":
                    loss = mse(pred, y_parc)
                else:
                    loss = mc_raw_loss_fixed(pred, y_raw, valid_gray_idx, parcel_for_gray, args.mc_samples)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())

            if args.log_every > 0 and ((step + 1) % args.log_every == 0 or (step + 1) == n_batches):
                window_avg = np.mean(train_losses[-(args.log_every):])
                print(f"  [E{epoch:02d} {step+1:>4}/{n_batches}]  loss={loss.item():.4f}  win_avg={window_avg:.4f}  cumavg={np.mean(train_losses):.4f}")

        # ── eval ──────────────────────────────────────────────────────────────────
        model.eval()
        if bubble_parc is not None:
            bubble_parc.eval()
        bench_accum = {k: [] for k in args.benchmarks}

        with torch.no_grad():
            for x_parc, x_raw, y_parc, y_raw in val_dl:
                x_parc = x_parc.to(device)
                y_parc = y_parc.to(device)
                if need_raw:
                    x_raw = x_raw.to(device)
                    y_raw = y_raw.to(device)

                if bubble_parc is not None:
                    W_c, W_s = bubble_parc.weights()
                    x_in     = bubble_parc(x_raw, W_c, W_s)
                else:
                    W_c = W_s = None
                    x_in = x_parc

                dec_in = x_in[:, -1:, :]
                pred   = model(x_in, dec_in)

                for bm_key in args.benchmarks:
                    if bm_key == "mmp":
                        if use_bubbles:
                            pred_g   = torch.cat([pred[:,:,:N_c] @ W_c,
                                                  pred[:,:,N_c:] @ W_s], dim=-1)
                            pred_mmp = reparcellate(pred_g, valid_gray_idx, parcel_for_gray, N_parc)
                            bench_accum["mmp"].append(mse(pred_mmp, y_parc).item())
                        else:
                            bench_accum["mmp"].append(mse(pred, y_parc).item())
                    elif bm_key == "mc_raw":
                        draws = []
                        for _ in range(args.mc_draws):
                            if use_bubbles:
                                v = mc_raw_loss_bubble(pred, y_raw, W_c, W_s, N_c, G_c, args.mc_samples)
                            else:
                                v = mc_raw_loss_fixed(pred, y_raw, valid_gray_idx, parcel_for_gray, args.mc_samples)
                            draws.append(v.item())
                        bench_accum["mc_raw"].append(np.mean(draws))
                    elif bm_key == "full_raw":
                        if use_bubbles:
                            pred_g = torch.cat([pred[:,:,:N_c] @ W_c,
                                                pred[:,:,N_c:] @ W_s], dim=-1)
                            bench_accum["full_raw"].append(mse(pred_g, y_raw).item())
                        else:
                            pred_g   = pred[:, :, parcel_for_gray]
                            actual_g = y_raw[:, :, valid_gray_idx]
                            bench_accum["full_raw"].append(mse(pred_g, actual_g).item())

        bench_str = "  ".join(f"{k}: {np.mean(v):.4f}" for k, v in bench_accum.items() if v)
        print(f"Epoch {epoch:>2}  train {mode_str}: {np.mean(train_losses):.4f}  |  {bench_str}")

        if args.wandb:
            log = {"epoch": epoch, f"train/{mode_str}": np.mean(train_losses)}
            for k, v in bench_accum.items():
                if v:
                    log[f"val/{k}"] = np.mean(v)
            wandb.log(log)

        torch.save(model.state_dict(), out_path)
        if bubble_parc is not None:
            torch.save(bubble_parc.state_dict(), run_dir / "bubbles.pt")

    print(f"Done. Model saved to {out_path}")
    if args.wandb:
        wandb.finish()


if __name__ == "__main__":
    main()
